url: http://philipsdyoo.github.io
baseurl: 

# Site Settings
title: Philip Yoo
description: "A curious developer willing to learn, experiment, and have fun in the New York Metropolitan Area"
keywords: "jekyll, theme"
google-tracking-id: "UA-82450130-1"

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
